### ISSUE TITLE
Option<Option<T>> don't work

### ISSUE THREAD

**Issue by leonardocustodio** [gmajor-encrypt/php-scale-codec#19]
There is the possibility of having `Option<Option<T>>` types. Unfortunately, this lib is not capable of encoding/decoding those.
Though I'm not sure what we would return for `0100` to make it different from `00`

Here are some tests for checking:
   ```
        $codec = new ScaleInstance(Base::create());
        $this->assertEquals(null, $codec->process("Option<Option<bool>>", new ScaleBytes("00")));
        $this->assertEquals(false, $codec->process("Option<Option<bool>>", new ScaleBytes("010100")));
        $this->assertEquals(true, $codec->process("Option<Option<bool>>", new ScaleBytes("010101")));
```

**Comment by gmajor-encrypt** [comment]
hi, @leonardocustodio 
option<bool> This is different from other types in decode
https://github.com/gmajor-encrypt/php-scale-codec/blob/master/src/Codec/Types/Option.php#L25

**Comment by gmajor-encrypt** [comment]
There has other reference https://github.com/gmajor-encrypt/scale-codec-comparator/blob/main/src/lib.rs#L323-L326

**Comment by leonardocustodio** [comment]
I see, so it is encoded this way?
```
Some(Some(true)) = 0c
Some(Some(false)) = 01
Some(None) = 02
None = 00
```

**Comment by gmajor-encrypt** [comment]
@leonardocustodio 
```
Some(Some(true)) = 01 01
Some(Some(false)) = 01 02 

Some(None) = 02 ?  I don't understand it
```

**Comment by leonardocustodio** [comment]
Ok I see, it works well, thank you for your feedback

**Comment by leonardocustodio** [comment]
Sorry I had to reopen because of this Option<bool> in theory it should be:
```
None = 00
Some(true) = 01 01
Some(false) = 01 00
```
But I'm getting
```
None = 00
Some(true) = 01
Some(false) = 02
```

Here is how Polkadot-JS encodes it:
![image](https://user-images.githubusercontent.com/5619696/197518451-d4c8af35-402b-403c-80da-d0a2436d606b.png)
![image](https://user-images.githubusercontent.com/5619696/197518486-620e5c6a-c4cd-42dd-a7f8-afdc0172f829.png)
![image](https://user-images.githubusercontent.com/5619696/197518520-1ce95d3a-f666-413f-8116-d3b5813e40e6.png)

**Comment by gmajor-encrypt** [comment]
@leonardocustodio Yes, i see. I'm currently working on a project that compares all scale codes, and the results of polkadots.js running here are inconsistent with parity-scale-codec

https://github.com/gmajor-encrypt/scale-codec-comparator/blob/main/src/lib.rs#L27
https://github.com/gmajor-encrypt/scale-codec-comparator/blob/main/polkadot-js/test/base.spec.ts#L86-L87

**Comment by Lohann** [comment]
An `Option` is an enum in rust, here is the proof:
```toml
[dependencies]
parity-scale-codec = "3.2.1"
parity-scale-codec-derive = "3.1.3"
hex = "0.4"
```

```rust
use parity_scale_codec::Encode;

fn main() {
    let v0: Option<bool> = None;
    let v1: Option<bool> = Some(false);
    let v2: Option<bool> = Some(true);
    println!("{:?}", hex::encode(v0.encode()));
    println!("{:?}", hex::encode(v1.encode()));
    println!("{:?}", hex::encode(v2.encode()));
}
```

output:
```
"00"
"0100"
"0101"
```

**Comment by leonardocustodio** [comment]
This also means this first comment was correct: https://github.com/gmajor-encrypt/php-scale-codec/issues/19#issue-1406770521
Can we fix this behavior @gmajor-encrypt ?

**Comment by gmajor-encrypt** [comment]
@leonardocustodio Ok, i will fix it tomorrow

**Comment by gmajor-encrypt** [comment]
@leonardocustodio This issue has been fixed. Thank you for feedback

**Comment by leonardocustodio** [comment]
Awesome, `Option<bool>` seems to be working fine now. Thanks a lot. But we still have an issue with `Option<Option<T>>`
Consider this custom type for example:

{
  "MutateToken": {
    "collectionId": "Compact<u128>",
    "tokenId": "Compact<u128>",
    "mutation": "TokenMutation"
  },
  "TokenMutation": {
    "behavior": "Option<Option<TokenMarketBehavior>>",
    "listingForbidden": "Option<bool>"
  },
  "TokenMarketBehavior": {
    "_enum": {
      "IsCurrency": "Null"
    }
  }
}

If we try to encode this:
```
collectionId = 57005
tokenId = 255
behavior = null
listingForbidden = null
```
We get the expected result:
`b67a0300fd030000`

If we try to encode:
```
collectionId = 57005
tokenId = 255
behavior = null
listingForbidden = true
```
We get the expected result:
`b67a0300fd03000101`

If we try to encode:
```
collectionId = 57005
tokenId = 255
behavior = IsCurrency
```
We get the expected result:
`b67a0300fd0301010100`

But there is no way to encode
behavior = Some(None)

Also, if we try to decode the following:
b67a030000 => That would be behavior none
b67a03010000 => That would be behavior Some(None)

We get the same output:
```
  "collectionId" => "57005"
  "tokenId" => "255"
  "mutation" => array:2 [
    "behavior" => null
    "listingForbidden" => null
  ]
```

**Comment by leonardocustodio** [comment]
Using polkadot-js API we can encode all options like this

```
const outerOptionType = 'Option<Option<EpMultiTokensTokenTokenMarketBehavior>>'
const innerOptionType = 'Option<EpMultiTokensTokenTokenMarketBehavior>'
const noneNoneTx = api.tx.multiTokens.mutateToken(2000, 1, { behavior: api.createType(outerOptionType) })
const someNoneTx = api.tx.multiTokens.mutateToken(2000, 1, { behavior: api.createType(outerOptionType, api.createType(innerOptionType)) })
```

**Comment by leonardocustodio** [comment]
In my opinion maybe we could use an empty array `[]` to encode `Some(None)` in `Option<Option<T>>`
